#!/bin/bash

TIMESTAMP=$(date +"%F")
BACKUP_DIR="backup/$TIMESTAMP"
#MYSQL_USER="backup"
MYSQL=/usr/bin/mysql
#MYSQL_PASSWORD="password"
MYSQLDUMP=/usr/bin/mysqldump

mkdir -p "$BACKUP_DIR/mysql"

databases=`$MYSQL -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema)"`

for db in $databases; do
  $MYSQLDUMP --force --opt --databases $db | gzip > "$BACKUP_DIR/mysql/$db.gz"
done